site_name: EcoPulse Smart City Demo (LDM Samples)
site_description: Documentation for the official Liferay Docker Manager samples repository.
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: README.md
  - Tutorials:
      - Quick Start: tutorials/quick_start.md
  - How-To:
      - Add a new Client Extension: how-to/add_client_extension.md
  - Reference:
      - LCP & Docker Configuration: reference/configuration.md
  - Explanation:
      - Architecture: explanation/architecture.md
      - Roadmap: explanation/roadmap.md
